backend:
  name: git-gateway
  branch: main # change to your default branch if different

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "src/pages/index.astro"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Body (raw Astro)", name: "body", widget: "markdown" }
